#!/usr/bin/env python
# Autogenerated file (by doconce sphinx_dir)
# Purpose: create HTML Sphinx version of web4sa

# Command-line arguments are transferred to the doconce format sphinx file
# compilation command

import glob, sys, os, commands, shutil

command_line_options = ' '.join(['"%s"' % arg for arg in sys.argv[1:]])

sphinx_rootdir = 'sphinx-rootdir'

def system(cmd, capture_output=False, echo=True):
    if echo:
        print 'running', cmd
    if capture_output:
        failure, outtext = commands.getstatusoutput(cmd) # Unix/Linux only
    else:
        failure = os.system(cmd)
    if failure:
        print 'Could not run', cmd
        sys.exit(1)
    if capture_output:
        return outtext

# Copy generated sphinx files to sphinx root directory
for part in ['._part0000_web4sa', '._part0001_web4sa', '._part0002_web4sa', '._part0003_web4sa', '._part0004_web4sa', '._part0005_web4sa', '._part0006_web4sa', '._part0007_web4sa', '._part0008_web4sa', '._part0009_web4sa', '._part0010_web4sa', '._part0011_web4sa', '._part0012_web4sa', '._part0013_web4sa', '._part0014_web4sa']:
    shutil.copy('%s.rst' % part, sphinx_rootdir)

# Copy figures and movies directories
figdirs = glob.glob('fig*') + glob.glob('mov*')
for figdir in figdirs:
    destdir = os.path.join(sphinx_rootdir, figdir)
    if os.path.isdir(figdir) and not os.path.isdir(destdir):
        print 'copying', figdir, 'to', sphinx_rootdir
        shutil.copytree(figdir, destdir)

# Copy needed media files in current dir (not in fig* and mov*)
rst_text = ''
for rstfile in glob.glob('*.rst'):
    rstfile += open(rstfile, 'r').read()
import re
media_files = re.findall('.. figure:: (.+)', rstfile)
media_files = [name for name in media_files
               if not os.sep in name]
for name in media_files:
    print 'copying', name, 'to', sphinx_rootdir
    shutil.copy(name, sphinx_rootdir)

# Copy linked local files, placed in _static*, to sphinx-rootdir/_static
staticdirs = glob.glob('_static*')
for staticdir in staticdirs:
    system('cp -r %s/* sphinx-rootdir/_static/' % staticdir)
    # (Note: must do cp -r since shutil.copy/copytree cannot copy a la cp -r)

# Compile web version of the sphinx document
os.chdir(sphinx_rootdir)
print os.getcwd()
system('make clean')
system('make html')

print 'Fix double title in <title> tags in .html files:'
os.chdir('_build/html')
for filename in glob.glob('*.html'):
    system('doconce subst "<title>(.+?) &mdash;.+?</title>" "<title>\g<1></title>" %s' % filename)
print """
google-chrome sphinx-rootdir/_build/html/index.html
"""
